services:
- type: web
  name: minio
  healthCheckPath: /minio/health/live
  env: docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
  autoDeploy: false
  disk:
    name: data
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    value: hps
  - key: MINIO_ROOT_PASSWORD
    value: Kg6yUaqW!
  - key: PORT
    value: 9000
